# Use the SDK image to build and publish the project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["SpamSentinel.csproj", "./"]
RUN dotnet restore "./SpamSentinel.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet publish "SpamSentinel.csproj" -c Release -o /app/publish

# Use nginx to serve the published app
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
# Remove default nginx static assets
RUN rm -rf ./*
COPY --from=build /app/publish/wwwroot .
COPY ["/nginx.conf", "/etc/nginx/nginx.conf"]
